theme: jekyll-theme-minimal
title: Szablon Raportu audytu KSC 
description: "Założenia projektu:
  pierwszoplanowy: porównywalności systemu na potrzeby:
  dalszoplanowe:
- szybka weryfikacji poprawności realizaji przez ministra właściwego
- realizacji funkcji normalizującej ocenę systemu cyberbezpieczeństwa
- zgodności wykonania czynności kontrolnych
- uzyskanie synergii w zakresie OPZ"
show_downloads: "true"
google_analytics: UA-154593377-1
