theme: jekyll-theme-architect
title: Raport z audytu zgodnego z Ustawą o Krajowym Systemie CyberBezpieczeństwa 
description: "Projekt tworzący możliwość uzyskania porównywalności systemu na potrzeby:
- weryfikacji poprawności działania przez ministra właściwego
- realizacji funkcji normalizującej rzeczywitą implementacje systemu
- zgodności wykonania czynności kontrolnych"
show_downloads: "true" 
google_analytics: [Your Google Analytics tracking ID]
