theme: jekyll-theme-minimal
title: Szablon Raportu audytu KSC 
description: "Projekt utworzenia systemu ładu korporacyjnego w zakresie OUK na potrzeby wykonywania weryfikacji poprawności realizaji zgoności KSC przez  ministra właściwego. Raport przy powszechonści implementacji normalizuje ocenę systemu cyberbezpieczeństwa, zgodności i powtarzalności wykonania czynności audytowych, jak również uzyskanie synergii w zakresie przygowania OPZ"
show_downloads: "true"
google_analytics: UA-154593377-1
